spring:
  profiles:
    active: local
---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  config:
    activate:
      on-profile: local


logging:
  level:
    org.hibernate.sql: debug

jwt:
  secret-key: 31E26CB6F1A84A31E6B23697937DB8CC3687FE4041492D6B6A61E235DD67DC81
  token:
    expire-time-ms: 3600000