spring:
  profiles:
    active: local # 기본 환경 선택
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    use-legacy-processing: true
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  config:
    activate:
      on-profile: local

# 운영 환경
---
spring.profiles.include: real-db
spring:
  config:
    activate:
      on-profile: set1
---
spring.profiles.include: real-db
spring:
  config:
    activate:
      on-profile: set2

management:
  endpoints:
    web:
      exposure:
        include: health


#jwt
jwt:
  secret-key: 31E26CB6F1A84A31E6B23697937DB8CC3687FE4041492D6B6A61E235DD67DC81
  token:
    expire-time-ms: 3600000


